# Site settings
title: ShakaCode
email: your-email@domain.com #not used
contact_email: contact@shakacode.com
description: > # this means to ignore newlines until "baseurl:"
  We build web and mobile applications using React, React-Native, and Ruby on Rails.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://localhost:4000" # the base hostname & protocol for your site
# url: "http://shakacode.github.io" # the base hostname & protocol for your site
url: "http://www.shakacode.com" # the base hostname & protocol for your site
forum_url: "http://forum.shakacode.com/"
github_shaka_opensource_url: "https://github.com/shakacode"
twitter_username: jekyllrb
github_username:  jekyll
facebook_url: "https://facebook.com/shakacode"
twitter_url: "https://twitter.com/shakacode"
discourse_url: "http://forum.shakacode.com/"

paginate: 4
paginate_path: "/blog/page:num"

# Build settings
markdown: kramdown
sass:
  style: compressed

# plugins
gems:
  - octopress-asset-pipeline
  - octopress-filters

asset_pipeline:
  order_js:
    - jquery.js
    - main.js

exclude: [Guardfile]

excerpt_separator: <!--more-->
