# Site settings
title: Shaka Code
email: your-email@domain.com #not used
contact_email: contact@shakacode.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
forum_url: "http://forum.railsonmaui.com/"
github_shaka_opensource_url: "https://github.com/shakacode"
twitter_username: jekyllrb
github_username:  jekyll
facebook_url: "https://www.facebook.com/shakacode"

paginate: 4
paginate_path: "/blog/page:num"

# Build settings
markdown: kramdown
sass:
  style: compressed

# plugins
gems:
  - octopress-asset-pipeline

asset_pipeline:
  order_js:
    - jquery.js
    - main.js
