# Site settings
title: ShakaCode
email: your-email@domain.com #not used
contact_email: contact@shakacode.com
justin_email: justin@shakacode.com
description: > # this means to ignore newlines until "baseurl:"
  We build web and mobile applications using React, React-Native, and Ruby on Rails.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://localhost:4000" # the base hostname & protocol for your site
# url: "http://shakacode.github.io" # the base hostname & protocol for your site
url: "http://www.shakacode.com" # the base hostname & protocol for your site
forum_url: "http://forum.shakacode.com/"
github_shaka_opensource_url: "https://github.com/shakacode"
twitter_username: jekyllrb
github_username:  jekyll
facebook_url: "https://facebook.com/shakacode"
twitter_url: "https://twitter.com/shakacode"
discourse_url: "http://forum.shakacode.com/"

paginate: 4
paginate_path: "/blog/page:num"

# Build settings
markdown: kramdown
sass:
  style: compressed

# plugins
gems:
  - octopress-asset-pipeline
  - octopress-filters

asset_pipeline:
  order_js:
    - jquery.js
    - main.js

exclude: [Guardfile]

excerpt_separator: <!--more-->

team:
  - member:
    name: Justin Gordon
    image_path: justin.jpg
    description: Aloha! Inspired by the Ruby on Rails Community, Justin began blogging on <a href="http://www.railsonmaui.com" target="_blank">RailsOnMaui</a> and <a href="https://github.com/justin808" target="_blank">working on open source</a>. A philosophy of sharing, plus <a href="http://www.railsonmaui.com/blog/2014/10/03/integrating-webpack-and-the-es6-transpiler-into-an-existing-rails-project/" target="_blank">React/Webpack/Rails integration</a>, developed into <a href="http://www.shakacode.com/about" target="_blank">ShakaCode</a>! A family, coding, and surfing in Maui create a healthy life balance.
    facebook: justinhgordon
    twitter: railsonmaui
    wikipedia:
    github: justin808
    linkedin: railsonmaui
    dribbble:
    personal: http://www.railsonmaui.com
  - member:
    name: Alex Fedoseev
    image_path: alex.jpg
    description: Alex started in web-analytics & marketing, then web development with Ruby on Rails, and has recently been focusing on the React + Flux ecosystem with a Rails backend. Alex shares his experience through a <a href="http://alexfedoseev.com/" target="_blank">personal blog</a>, <a href="https://medium.com/@alexfedoseev" target="_blank">medium</a> & <a href="https://github.com/alexfedoseev" target="_blank">github</a>. Coding & surfing FTW!
    facebook: alex.fedoseev
    twitter: alexfedoseev
    wikipedia:
    github: alexfedoseev
    linkedin: alexfedoseev
    dribbble:
    personal: http://alexfedoseev.com
  - member:
    name: Alexey Karasev
    image_path: alexey.jpg
    description: Alexey has worked in investment business for several years, programming as a hobby in his free time. After some time, he decided to quit his investment job to pursue his real passion and started programming full-time. He has experience in backend development (Rails, Node, Golang, Hadoop), frontend (Angular, React) and native iOS apps development in Swift and Obj-C.
    facebook: karasev.alexey
    twitter: AlexeyKarasev1
    wikipedia:
    github: alleycat-at-git
    linkedin:
    dribbble:
    personal:
  - member:
    name: Ali Pearson
    image_path: ali.jpg
    description: Ali loves code, but only as a spectator for now. Meanwhile, she manages everything else at ShakaCode, so the coders can stay in THE ZONE. Ali also orchestrates all aspects of <a href="https://www.facebook.com/SugarRanch" target="_blank">Sugar Ranch Maui</a>, helps at the kids' school. She has no free time. :-)
    facebook: alipearso
    twitter: alipearso
    wikipedia:
    github: shakagirl
    linkedin: ali-pearson-9437b94
    dribbble:
    personal:
  - member:
    name: Andrey Ashgaliev
    image_path: andrey.jpg
    description: Andrey is a software developer from Kazakhstan. He has been engaged in various technologies in his career, from sysadmin tasks and developing scripts on VBA, to developing websites on the PHP / JS stack. Recently, he got passionate about React technology and everything connected to it. In his free time, he likes to spend with his family and friends.
    facebook: andrey.ashgaliev
    twitter:
    wikipedia:
    github: ashgaliyev
    linkedin: andrey-ashgaliyev-09b08932/
    dribbble:
    personal:
  - member:
    name: Eugene Arkhipov
    image_path: eugene.jpg
    description: Eugene is a passionate designer who loves creating beautiful and effective products. He believes that design is not just about how a product looks but also how it works, so he does his best to provide users with a great experience.
    facebook: earkhipov
    twitter:
    wikipedia:
    instagram:
    github:
    linkedin: evgenyarkhipov
    dribbble: arkhipov
    personal:
  - member:
    name: Judah Meek
    image_path: judah.jpg
    description: Judah comes to ShakaCode from Texas. He loves programming and professional web development. In his free time, he hacks open source, especially ShakaCode’s.
    facebook:
    twitter: judahmeek
    wikipedia:
    instagram:
    github: Judahmeek
    linkedin:
    dribbble:
    personal:
  - member:
    name: Marcus Sá
    image_path: marcus.jpg
    description: Marcus is a Software Engineer from Brazil who loves to transform code into products that make people more productive and less stressed. He also loves working remotely, watching American football, reading horror books, and playing with his Arduino.
    facebook: marcus.m.sa
    twitter: sa_vini
    wikipedia:
    instagram:
    github: mamute
    linkedin: marcus-sá-29125a32
    dribbble:
    personal:
  - member:
    name: Mario Perez
    image_path: mario.jpg
    description: Mario is a Computer Scientist from Spain. Ruby lover and refactoring maniac who enjoys working remotely. When he's not pointing out code smells, he's probably in a crossfit box or dancing salsa & bachata.
    facebook: mario.mariete19
    twitter: mapreal19
    wikipedia:
    instagram:
    github: mapreal19
    linkedin: marioperez19
    dribbble:
    personal: http://marioperez.me/
  - member:
    name: Renan Aguiar
    image_path: renan.jpg
    description: Renan discovered programming at university and quickly abandoned his original course of study to immerse himself in the coding world. He now works as a software engineer embracing Javascript and Ruby. Renan is 3.14 times more productive while listening to music.
    facebook: rffaguiar
    twitter: rffaguiar
    wikipedia:
    instagram:
    github: rffaguiar
    linkedin:
    dribbble:
    personal:
  - member:
    name: Sergey Tarasov
    image_path: sergey.jpg
    description: Sergey has worked as an international corporate lawyer and an executive in the heavy equipment industry. In pursuit of more balanced and enjoyable lifestyle, he's now pursuing his passion for programming. He loves yoga, healthy lifestyle & family time.
    facebook:
    twitter:
    wikipedia:
    github: dzirtusss
    linkedin:
    dribbble:
    personal: http://sergey-tarasov.com/
